#! /bin/sh

# set pulse when using old -soundhw option
if echo "$@" |grep -q soundhw; then
    export QEMU_AUDIO_DRV="pa"
    QEMU_PA_SERVER="/run/user/$(id -u)/pulse/native"
    export QEMU_PA_SERVER
fi

exec "$@"
